name: Go Test
on:
  push:
    branches:
    - master
  pull_request:
    branches-ignore:
    - release

jobs:
  build:
    name: testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.13'
    - name: go test and report
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: 055c4795f09fe218b101ab59ab6601e8fb5c60df89b60f5177b939a2682f819d
      with:
        coverageCommand: go test -coverprofile=c.out ./...
        coverageLocations: c.out:gocov
        prefix: github.com/blueworrybear/livelogs
